name: Build VPN App

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.9']
      fail-fast: false  # Continue with other OS builds even if one fails

    steps:
    - uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable pip caching

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install qt@5
        brew link qt@5
        brew install pyqt@5
        brew install openvpn
        echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> ~/.bash_profile
        source ~/.bash_profile

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-qt5 qt5-qmake build-essential libqt5x11extras5-dev qttools5-dev-tools openvpn libssl-dev libffi-dev

    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pywin32
        choco install openvpn -y

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller

    - name: Create executable (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --name="VPN App" --windowed --onefile --add-binary='/usr/local/opt/openvpn/sbin/openvpn:.' --hidden-import=PyQt5.sip --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets Main.py

    - name: Create executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --name="VPN App" --windowed --onefile --hidden-import=win32api --hidden-import=win32con --hidden-import=win32gui --hidden-import=PyQt5.sip --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets Main.py

    - name: Create executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --name="VPN App" --windowed --onefile --hidden-import=PyQt5.sip --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets Main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: VPN-App-${{ matrix.os }}
        path: dist/*
        if-no-files-found: error  # Fail if no files to upload
